trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MULE_ENV: 'Sandbox'
  APP_NAME: 'hello-mule'
  REGION: 'us-east-1'
  ANYPOINT_ORG_ID: $(ANYPOINT_ORG_ID)
  ANYPOINT_USERNAME: $(ANYPOINT_USERNAME)
  ANYPOINT_PASSWORD: $(ANYPOINT_PASSWORD)

steps:
- task: Maven@3
  displayName: 'Build Hello Mule Application'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenOptions: '-Xmx3072m'

- task: Bash@3
  displayName: 'Deploy to CloudHub'
  inputs:
    targetType: 'inline'
    script: |
      echo "Deploying to CloudHub..."
      mvn deploy -DmuleDeploy \
        -Danypoint.username=$(ANYPOINT_USERNAME) \
        -Danypoint.password=$(ANYPOINT_PASSWORD) \
        -Danypoint.environment=$(MULE_ENV) \
        -Danypoint.businessGroup=$(ANYPOINT_ORG_ID) \
        -Dcloudhub.applicationName=$(APP_NAME)
